name: Simple JS Workflow

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List JavaScript Files
        run: find . -name "*.js"

      - name: Workflow Triggered
        run: echo "Code pushed successfully!"
